version: '3.8'
services:
  app:
    container_name: cadeoqueijo-api
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./html/:/var/www/html/
    ports:
      - "5000:80"
    depends_on:
      - db
  
  db:
    image: mariadb
    container_name: cadeoqueijo-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root   
      MYSQL_DATABASE: database
    volumes:
      - cadeoqueijo_data:/var/lib/mysql
    ports:
      - "3306:3306"
    expose:
      - 3306

volumes:
  cadeoqueijo_data:
